model_name: deepconvcontext
model: {
  conv_kernels: 64,
  lstm_units: 128,
  lstm_layers: 1,
  dropout: 0.5,
  type: 'self-attention', # 'lstm', 'self-attention', 'transformer'
  bidirectional: True, # if type is 'lstm', 'self-attention' or 'transformer'
  attention_num_heads: 4, # if type is 'self-attention' or 'transformer'
  transformer_depth: 1, # if type is 'transformer'
  dim_feedforward: 768, # if type is 'transformer' or 'self-attention'
}